### ISSUE TITLE
My app keep crashing when about to launch

### ISSUE THREAD

**Issue by Inihood1** [Caqil/wireguard_flutter#25]
E/AndroidRuntime( 8674): FATAL EXCEPTION: DefaultDispatcher-worker-1
E/AndroidRuntime( 8674): Process: com.radiantmoney.app, PID: 8674
E/AndroidRuntime( 8674): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
E/AndroidRuntime( 8674): 	at android.net.VpnService.prepare(VpnService.java:206)
E/AndroidRuntime( 8674): 	at billion.group.wireguard_flutter.WireguardFlutterPlugin.checkPermission(WireguardFlutterPlugin.kt:275)
E/AndroidRuntime( 8674): 	at billion.group.wireguard_flutter.WireguardFlutterPlugin.access$checkPermission(WireguardFlutterPlugin.kt:39)
E/AndroidRuntime( 8674): 	at billion.group.wireguard_flutter.WireguardFlutterPlugin$setupTunnel$1.invokeSuspend(WireguardFlutterPlugin.kt:269)
E/AndroidRuntime( 8674): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime( 8674): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
E/AndroidRuntime( 8674): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
E/AndroidRuntime( 8674): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
E/AndroidRuntime( 8674): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
E/AndroidRuntime( 8674): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
E/AndroidRuntime( 8674): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
E/AndroidRuntime( 8674): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
E/AndroidRuntime( 8674): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@96049dd, Dispatchers.IO]
I/ExceptionHandle( 8674): at android.net.VpnService.prepare(VpnService.java:206)
I/ExceptionHandle( 8674): at billion.group.wireguard_flutter.WireguardFlutterPlugin.checkPermission(WireguardFlutterPlugin.kt:275)
I/ExceptionHandle( 8674): at billion.group.wireguard_flutter.WireguardFlutterPlugin.access$checkPermission(WireguardFlutterPlugin.kt:39)
I/ExceptionHandle( 8674): at billion.group.wireguard_flutter.WireguardFlutterPlugin$setupTunnel$1.invokeSuspend(WireguardFlutterPlugin.kt:269)
I/ExceptionHandle( 8674): at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
I/ExceptionHandle( 8674): at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
I/ExceptionHandle( 8674): at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
I/ExceptionHandle( 8674): at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
I/ExceptionHandle( 8674): at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
I/ExceptionHandle( 8674): at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
I/ExceptionHandle( 8674): at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
I/ExceptionHandle( 8674): at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
I/Process ( 8674): Sending signal. PID: 8674 SIG: 9
Lost connection to device.

**Comment by Caqil** [comment]
hello, what version android?

**Comment by Muzammil-crypto** [comment]
@Caqil I am also facing the same issue. after integrating stripe, as i changed the MainActivity.kt (changed Flutter Activity to FlutterFragmentActivity) it started giving me the same error. 


```
ext.kotlin_version = '1.8.10'
```


```
classpath 'com.android.tools.build:gradle:8.3.2'
```

Also
@Inihood1 did you find any solutions for this error? Please let me know thanks!

**Comment by elix1er** [comment]
bump
