### ISSUE TITLE
VPN status incorrect and disconnect not working in certain scenarios

### ISSUE THREAD

**Issue by evangelme** [Caqil/wireguard_flutter#28]
On Android, when you connect to the VPN and then close the app, if the VPN disconnects in the background (imagine you have a periodic function), the VPN does not disconnect. However, when you reopen the app, the VPN status in the Android settings shows as connected, but the app shows the VPN as disconnected. You cannot do anything to disconnect it. Please fix this. Thank you.

**Comment by evangelme** [comment]
i run your example code and test it again this is the logs in that situation
can you help me with this problem i wrote the app with flutter but sometimes in that situation i explained vpn says is disconnect but it connects in setting the logs are like this


E/NVPN    ( 9495): Connect - Can't connect to tunnel: java.lang.Exception: Permissions are not given
E/NVPN    ( 9495): java.lang.Exception: Permissions are not given
E/NVPN    ( 9495):      at billion.group.wireguard_flutter.WireguardFlutterPlugin$connect$1.invokeSuspend(WireguardFlutterPlugin.kt:236)
E/NVPN    ( 9495):      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/NVPN    ( 9495):      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
E/NVPN    ( 9495):      at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
E/NVPN    ( 9495):      at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
E/NVPN    ( 9495):      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
E/NVPN    ( 9495):      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
E/NVPN    ( 9495):      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
E/NVPN    ( 9495):      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
I/flutter ( 9495): failed to start PlatformException(Permissions are not given, null, null, null)
I/flutter ( 9495): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:651:7)
I/flutter ( 9495): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
I/flutter ( 9495): <asynchronous suspension>
I/flutter ( 9495): #2      _MyAppState.startVpn (package:testvpn/main.dart:57:7)
I/flutter ( 9495): <asynchronous suspension>
I/flutter ( 9495):
I/flutter ( 9495): getting stage
I/flutter ( 9495): stage: VpnStage.disconnected
I/flutter ( 9495): getting stage
I/flutter ( 9495): stage: VpnStage.disconnected
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Handshake did not complete after 5 seconds, retrying (try 13)
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Sending handshake initiation
I/flutter ( 9495): getting stage
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Handshake did not complete after 5 seconds, retrying (try 3)
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Sending handshake initiation
I/flutter ( 9495): stage: VpnStage.disconnected
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Handshake did not complete after 5 seconds, retrying (try 14)
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Sending handshake initiation
I/flutter ( 9495): getting stage
I/flutter ( 9495): stage: VpnStage.disconnected
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Handshake did not complete after 5 seconds, retrying (try 4)
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Sending handshake initiation
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Handshake did not complete after 5 seconds, retrying (try 15)
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Sending handshake initiation
I/flutter ( 9495): initialize success my_wg_vpn
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Handshake did not complete after 5 seconds, retrying (try 2)
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Sending handshake initiation
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Handshake did not complete after 5 seconds, retrying (try 16)
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Sending handshake initiation
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Handshake did not complete after 5 seconds, retrying (try 2)
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Sending handshake initiation
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Handshake did not complete after 5 seconds, retrying (try 17)
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Sending handshake initiation
D/WireGuard/GoBackend/my_wg_vpn( 9495): peer(6uZg…HliQ) - Sending handshake
