### ISSUE TITLE
Crashin when using FlutterFragmentActivity

### ISSUE THREAD

**Issue by ilkeryildirim** [Caqil/wireguard_flutter#41]
i just wanted use revenue cat paywalls and it needs FlutterFragmentActivity 

import io.flutter.embedding.android.FlutterFragmentActivity

class MainActivity : FlutterFragmentActivity() {
}

then

E/AndroidRuntime(25491): FATAL EXCEPTION: DefaultDispatcher-worker-1
E/AndroidRuntime(25491): Process: com.beevpn.androidvpn, PID: 25491
E/AndroidRuntime(25491): java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
E/AndroidRuntime(25491): 	at android.net.VpnService.isKGClientPackageInstalled(VpnService.java:243)
E/AndroidRuntime(25491): 	at android.net.VpnService.prepare(VpnService.java:281)
E/AndroidRuntime(25491): 	at billion.group.wireguard_flutter.WireguardFlutterPlugin.checkPermission(WireguardFlutterPlugin.kt:275)
E/AndroidRuntime(25491): 	at billion.group.wireguard_flutter.WireguardFlutterPlugin.access$checkPermission(WireguardFlutterPlugin.kt:39)
E/AndroidRuntime(25491): 	at billion.group.wireguard_flutter.WireguardFlutterPlugin$setupTunnel$1.invokeSuspend(WireguardFlutterPlugin.kt:269)
E/AndroidRuntime(25491): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
E/AndroidRuntime(25491): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
E/AndroidRuntime(25491): 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
E/AndroidRuntime(25491): 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
E/AndroidRuntime(25491): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
E/AndroidRuntime(25491): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
E/AndroidRuntime(25491): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
E/AndroidRuntime(25491): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
E/AndroidRuntime(25491): 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5ae0946, Dispatchers.IO]

**Comment by ilkeryildirim** [comment]
#42
